name: green_kharkiv
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  location_web: ^3.1.1
  mapbox_gl_web: ^0.14.0
  shared_preferences_web: ^2.0.3
  font_awesome_flutter: ^9.2.0
  mapbox_gl: ^0.14.0
  flutter_speed_dial: ^5.0.0+1
  location: ^4.3.0
  fluttericon: ^2.0.0
  icofont_flutter: ^1.4.0
  community_material_icon: ^5.9.55
  shared_preferences: ^2.0.13
  lottie: ^1.2.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  galleryimage: ^1.1.0
  qr_code_scanner: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/circle.png
    - assets/images/profile.jpg
    - assets/images/square.png
    - assets/images/rhombus.png
    - assets/lottie/login2.json