class NameConfig {
  static const Map<String, String> NAME = {
    'ef_green_space': 'Зелені насадження',

    'efgs_id': 'ID об`єкта',
    'efgs_name': 'Назва об`єкта',
    'efgs_name_lat': 'Назва (латинська мова)',
    'efgs_name_rus': 'Назва ( російська мова)',
    'efgs_invent_number': 'Інвентарний номер',
    'efgs_barcode': 'Штрих-код',
    'geom_local': 'Мізце розташування координати (УСК- 2000)',
    'geom': 'WGS 84',
    'efgs_address': 'Найближча адреса',
    'efgs_sort': 'Рід',
    'efgs_age': 'Вік, років',
    'efgs_height': 'Висота',
    'efgs_diameter': 'Діаметр стовбура на висоті 1.3 м, см',
    'efgs_number': 'Кількість(шт./м2)',
    'efgs_square': 'Площа(м2)',
    'efgs_status': 'Якісний стан',
    'efgs_cost': 'Вартість, грн',
    'efgs_recommend': 'Рекомендації',
    'efgs_info': 'Примітка',
    'efgs_image': 'Фото',
    'efgs_type': 'Тип насадження',
    'files': '',
    'cdate': '',
    'uid': '',
    'editor_id': '',
    'editor_date': '',
    'is_verified': 'false - не верифіковано, true - веріфіковано',
    'efgs_object': 'Рекреаційна зона',
    'address_id': 'Адреса (адресний реєстр)',
    'x': 'Координата X',
    'y': 'Координата Y',
    'tree_speci': 'Порода',
    'trunk_circ': 'Окружність стовбура, см',
    'birth_year': 'Рік висадки',
    'soil_condi': 'Лунка',
    'discrete_s': 'Рівень наклону в градусах',
    'undercut': 'Підрізка',
    'bark_damag': 'Пошкодження кори в процентах',
    'fungus': 'Гриби',
    'woodworms': 'Древоточець',
    'rottenness': 'Трухлявість',
    'hollow': 'Дупла',
    'frost_bump': 'Морозобоїни',
    'burns': 'Опіки',
    'nails': 'Цвяхи',
    'lamps_and_': 'Лампи та дроти',
    'trunk_inje': 'Інєкції в стовбур',
    'crown_bare': 'Оцінка стану крони (частка голих гілок в вегетаційний період)',
    'needs_trea': 'Потребує лікування',
    'comment': 'Коментар',
    'is_add_attr': 'Ознака чи добавлено атрибутивні властивості',
    'efgs_type_flower': 'Тип квітника',
    'efgs_type_lawn': 'Тип газона',
    'efgs_type_hedge': 'Тип Живоплот',
    'length': 'Протяжність, м',
    'efgs_type_bush': 'Порода кущів',
    'diameter_stump': 'Діаметр пенька, м',


    'ef_street_furniture': 'Малі архітектурні форми і дороги',

    'efsf_id': 'ID об`єкта',
    'efsf_name': 'Назва об`єкта',
    'efsf_material': 'Матеріал, з якого виготовлено об`єкт',
    'efsf_square': 'Площа, кв. м',
    'efsf_image': '',
    'efsf_respons': 'Відповідальний за утримання',
    'efsf_overhaul': 'Капітальний ремонт',
    'efsf_current_repair': 'Поточний ремонт',
    'efsf_saf_road': 'Категорія',
    'efsf_road_mat': 'Покриття доріг',
    'efsf_obj': 'Рекреаційна зона',
    'efsf_road_cat': 'Вид',
    'doc_files': '',
    'invent_number': 'Інвентарний номер',


    'ef_multimedia_files': '',

    'efmf_id': 'ID об`єкта',
    'obj_id': '',
    'image': '',
    'sid': 'ознака звідки загружений файл : 1- Публічка , 35 - адмінка',
    'type': 'тип фото',
    'is_main': 'Ознака чи голвна фотка',
    'enabled': '',
    'efgs_hist_id': '',

    'null': 'Інформація відсутня',
  };
}
